baseURL = 'https://elixir.tw/'
languageCode = 'zh-tw'
title = 'Elixir Taiwan'
theme = 'elixirtw'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "${GOOGLE_ANALYTICS_ID}"

[params]
# Meta description
description = "台灣 Elixir 程式語言社群 - 致力於推廣函數式程式設計與 Elixir 生態系"

# CJK language support
hasCJKLanguage = true

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2006-01-02'

# Social links (used in header/footer)
[params.social]
facebook = "https://www.facebook.com/groups/elixir.tw"
x = "https://x.com/elixirtw"
discord = "https://discord.com/invite/9zBmPfrrVP"
youtube = "https://www.youtube.com/channel/UCzCRwQKbdBbW9-Vpr--ydZg"
github = "https://github.com/elixirtw"

# Main menu
[menu]
[[menu.main]]
name = "首頁"
url = "/"
weight = 1

[[menu.main]]
name = "關於社群"
url = "/about/"
weight = 2

[[menu.main]]
name = "關於 Elixir"
url = "/what-is-elixir/"
weight = 3

[[menu.main]]
name = "Why Elixir"
url = "/why-elixir/"
weight = 4

[[menu.main]]
name = "Meetup 小聚"
url = "/meetup/"
weight = 5

[[menu.main]]
name = "學習資源"
url = "/resources/"
weight = 6

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 7


[[menu.main]]
name = "顧問諮詢"
url = "/consulting/"
weight = 8

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'dracula'
lineNos = true
lineNumbersInTable = true

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Languages
[languages]
[languages.zh]
contentDir = 'content'
languageCode = 'zh-TW'
languageName = '繁體中文'
weight = 1
[languages.zh.params]
reading_speed = 500

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 2
[languages.en.params]
reading_speed = 228

# Giscus comments
[params.giscus]
enable = true
repo = "elixirtw/elixirtw.github.io"
repoid = "${GISCUS_REPO_ID}"
category = "Announcements"
categoryid = "${GISCUS_CATEGORY_ID}"
mapping = "pathname"
theme = "transparent_dark"
datalang = "zh-TW"
