baseURL = 'https://elixir.tw/'
languageCode = 'zh-tw'
title = 'Elixir Taiwan Blog'
theme = 'typo'
hasCJKLanguage = true

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "${GOOGLE_ANALYTICS_ID}"

[params]
# Meta description
description = "A Tech Blog of Elixir Taiwan"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = '歡迎!'
homeIntroContent = """
這裡是 Elixir Taiwan 的部落格。我們自 2014 開始舉辦每個月定期的實體聚會，目前持續運作中，聚會詳情請參考 [facebook](https://www.facebook.com/groups/elixir.tw)/[meetup](https://www.meetup.com/elixirtw-taipei) 連結。這裡我們會分享各種程式相關的新聞、知識與新議題。
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = 'Jan 2 2006'

# Breadcrumbs
breadcrumbs = false

# CJK lanugage

# Social icons
[[params.social]]
name = "facebook"
url = "https://www.facebook.com/groups/elixir.tw"

[[params.social]]
name = "X"
url = "https://x.com/elixirtw"

[[params.social]]
name = "Discord"
url = "https://discord.com/invite/9zBmPfrrVP"

[[params.social]]
name = "Meetup"
url = "https://www.meetup.com/elixirtw-taipei"

[[params.social]]
name = "Youtube"
url = "https://www.youtube.com/channel/UCzCRwQKbdBbW9-Vpr--ydZg"

# Main menu pages
[[params.menu]]
name = "首頁"
url = "/"

[[params.menu]]
name = "文章"
url = "/posts"

[[params.menu]]
name = "學習資源"
url = "/resources"

[[params.menu]]
name = "關於我們"
url = "/about"

[[params.menu]]
name = "小聚"
url = "/meetup"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

## ReadingTime
[languages]
[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 2
[languages.en.params]
reading_speed = 228
[languages.zh]
contentDir = 'content'
languageCode = 'zh-TW'
languageName = '繁體中文'
weight = 1
[languages.zh.params]
reading_speed = 500

# Giscus comments
[params.giscus]
enable = true
repo = "elixirtw/elixirtw.github.io"
repoid = "${GISCUS_REPO_ID}"
category = "Announcements"
categoryid = "${GISCUS_CATEGORY_ID}"
mapping = "pathname"
theme = "preferred_color_scheme"
datalang = "zh-TW"
